// lab4_top.sv

// This file instantiates the lab4 module generated by Platform
// Designer and connects the FPGA pins to the module pins.

module lab4_top
  ( input  logic s1, clk50,
    output logic [7:0] LED,
    input logic ADC_SDO,
    output logic ADC_CONVST, ADC_SDI, ADC_SCK ) ;
   
   lab4 lab4_0 
     ( .clk50_clk(clk50), 
       .leds_export(LED),               
       .reset_n_reset_n(s1),
       .adc0_sdo(ADC_SDO), .adc0_convst(ADC_CONVST), 
       .adc0_sdi(ADC_SDI), .adc0_sck(ADC_SCK) ) ;
   
endmodule
